### PR TITLE
added conda recipe #20

### LINKED ISSUE #20: Add conda recipe
Adding a conda recipe would make distribution simpler, especially in combination with packages that require C/C++ libraries.

Cheers,
Sarthak

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes #20

### CODE REVIEW

**Comment by havakv** [comment]
Hmm... You've only made changes to the readme file, so these test shouldn't be failing. It's the matpllotlib dependency that fails for python 3.6 `Beginning with Matplotlib 3.4, Python 3.7 or above is required.`
I guess we could remove the tests for python 3.6, or do you see any other smart way to handle this?

**Comment by sarthakpati** [comment]
Hmm, I am not sure, perhaps you could also put a lower version of matplotlib?

**Comment by havakv** [comment]
I don't like restricting the matplotlib version, so I'll just require the checks to pass for 3.7. I'm not sure why 3.6 tries to install a version of matplotlib not compatible with 3.6, so maybe that will be fixed in the future

**Comment by havakv** [comment]
It might just be that the action does not install a `pip >= 9.0.1` which hopefully will fix itself in the future.

**Pull request merged**
